// M4/portfolio-reactjs/src/portfolio/estudiosComponent.js
import React from "react";
import "./estudiosComponent.scss";

export default class EstudiosComponent extends React.Component {
  render() {
    return misEstudios(this.props);
  }
}

function misEstudios(props) {
  return (
    <div>
      <div className="cabeceraEstudios">
        <h2>{props.cabecera}</h2>
      </div>
      <div className="estudios">
        <dl>
          <dt>Títulos académicos:</dt>
          <dd>Licenciado en Química por la Universidad de Valladolid</dd>
          <dt>Certificaciones:</dt>
          <dd>Professional Scrum Master I | Scrum.org</dd>
          <dd>
            ISTQB Certified Tester, Foundation Level | International Software
            Quality Institute
          </dd>
          <dt>Formación complementaria:</dt>
          <dd>(en curso) Máster en Full Stack Developer | Naxer</dd>
          <dt>Lenguajes de programación:</dt>
          <dd>Java, Typescript, python, SQL, pl/sql, Shell Script</dd>
        </dl>
        <dl>
          <dt>Frameworks y herramientas:</dt>
          <dd>Spring, Angular, ReactJS, Hibernate, Maven</dd>
          <dt>Servidores de Aplicaciones e IDEs:</dt>
          <dd>Tomcat, Jboss/Wildfly, eclipse, IntelliJ, Visual Studio</dd>
          <dt>Bases de Datos:</dt>
          <dd>Oracle, SQL Server, MySQL/MariaDB</dd>
        </dl>
      </div>
    </div>
  );
}

// M4/fullstack/src/app/portfolio/estudios/estudios.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-estudios',
  templateUrl: './estudios.component.html',
  styleUrls: ['./estudios.component.css'],
})
export class EstudiosComponent implements OnInit {
  titulos: string[] = [];
  otros: string[] = [];
  certificaciones: string[] = [];
  languages: string[] = [];
  frameworks: string[] = [];
  ides: string[] = [];
  dbs: string[] = [];

  @Input() cabecera: string = '';

  ngOnInit(): void {
    this.titulos = ['Licenciado en Química por la Universidad de Valladolid'];
    this.otros = ['(en curso) Máster en Full Stack Developer | Naxer'];
    this.certificaciones = [
      'Professional Scrum Master I | Scrum.org',
      'ISTQB Certified Tester, Foundation Level | International Software Quality Institute',
    ];
    this.languages = ['Java', 'Typescript', 'python', 'SQL', 'pl/sql', 'Shell Script'];
    this.frameworks = ['Spring', 'Angular', 'Hibernate', 'Maven'];
    this.ides = ['Tomcat', 'Jboss / Wildfly', 'eclipse', 'IntelliJ', 'Visual Studio'];
    this.dbs = ['Oracle', 'SQL Server', 'MySQL / MariaDB'];
  }
}

<h2>Formación y Habilidades:</h2>
<div class="d-flex flex-md-row gap-3 mb-2">
<dl>
  <dt>Títulos académicos:</dt>
  <dd *ngFor="let titulo of titulos">{{ titulo }}</dd>
  <dt>Certificaciones:</dt>
  <dd *ngFor="let cert of certificaciones">{{ cert }}</dd>
  <dt>Formación complementaria:</dt>
  <dd *ngFor="let otro of otros">{{ otro }}</dd>
  <dt>Lenguajes de programación:</dt>
  <dd *ngFor="let lang of languages">{{ lang }}</dd>
</dl>
<dl>
  <dt>Frameworks y herramientas:</dt>
  <dd *ngFor="let fw of frameworks">{{ fw }}</dd>
  <dt>Servidores de Aplicaciones e IDEs:</dt>
  <dd *ngFor="let ide of ides">{{ ide }}</dd>
  <dt>Bases de Datos:</dt>
  <dd *ngFor="let db of dbs">{{ db }}</dd>
</dl>
</div>
